include:
  - ./external-api/docker-compose.external-api.yaml
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/home/node/app
    ports: 
    - 3000:3000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
       # restart: true #se container falhar ele vai reiniciar pra tentar recuperar
    networks:
      - external-api_default
  db:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s # com que frequência o healthcheck é executado
      timeout: 5s # quanto tempo esperar antes de considerar o healthcheck falhado
      retries: 5 # número de tentativas antes de considerar o container como falhado    start_period: 10s  #Tempo de espera antes de iniciar o healthcheck
    networks:
      - external-api_default

networks:
  external-api_default:
    external: true